# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'combobox.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_yazilimdili(object):
    def setupUi(self, yazilimdili):
        yazilimdili.setObjectName("yazilimdili")
        yazilimdili.resize(400, 300)
        self.secici = QtWidgets.QComboBox(yazilimdili)
        self.secici.setGeometry(QtCore.QRect(40, 91, 103, 31))
        font = QtGui.QFont()
        font.setFamily("Apple SD Gothic Neo")
        font.setPointSize(13)
        font.setItalic(False)
        self.secici.setFont(font)
        self.secici.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.secici.setMouseTracking(False)
        self.secici.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.secici.setObjectName("secici")
        self.secici.addItem("")
        self.secici.addItem("")
        self.secilen = QtWidgets.QLineEdit(yazilimdili)
        self.secilen.setGeometry(QtCore.QRect(240, 90, 113, 21))
        self.secilen.setObjectName("secilen")
        self.secicilabel = QtWidgets.QLabel(yazilimdili)
        self.secicilabel.setGeometry(QtCore.QRect(10, 60, 171, 16))
        self.secicilabel.setObjectName("secicilabel")
        self.secilenlabel = QtWidgets.QLabel(yazilimdili)
        self.secilenlabel.setGeometry(QtCore.QRect(260, 60, 71, 16))
        self.secilenlabel.setObjectName("secilenlabel")
        self.cikisbutonu = QtWidgets.QPushButton(yazilimdili)
        self.cikisbutonu.setGeometry(QtCore.QRect(260, 230, 100, 32))
        self.cikisbutonu.setObjectName("cikisbutonu")
        
        self.secici.addItems(["Java", "C#"])
        self.secici.currentIndexChanged.connect(self.secilen_combobox)
        self.cikisbutonu.clicked.connect(yazilimdili.close)

        self.retranslateUi(yazilimdili)
        QtCore.QMetaObject.connectSlotsByName(yazilimdili)

    def retranslateUi(self, yazilimdili):
        _translate = QtCore.QCoreApplication.translate
        yazilimdili.setWindowTitle(_translate("yazilimdili", "Dialog"))
        self.secici.setItemText(0, _translate("yazilimdili", "Python"))
        self.secici.setItemText(1, _translate("yazilimdili", "C++"))
        self.secicilabel.setText(_translate("yazilimdili", "Programlama dilinizi seciniz"))
        self.secilenlabel.setText(_translate("yazilimdili", "Secilen dil"))
        self.cikisbutonu.setText(_translate("yazilimdili", "Cikis Butonu"))
        
    def secilen_combobox(self):
        secilendil = self.secici.currentText()
        self.secilen.setText(secilendil)
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    yazilimdili = QtWidgets.QDialog()
    ui = Ui_yazilimdili()
    ui.setupUi(yazilimdili)
    yazilimdili.show()
    sys.exit(app.exec_())
