# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hesap_makinesi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_hesap_makinesi(object):
    def setupUi(self, hesap_makinesi):
        hesap_makinesi.setObjectName("hesap_makinesi")
        hesap_makinesi.resize(400, 314)
        self.yedi = QtWidgets.QPushButton(hesap_makinesi)
        self.yedi.setGeometry(QtCore.QRect(50, 140, 41, 41))
        self.yedi.setObjectName("yedi")
        self.bir = QtWidgets.QPushButton(hesap_makinesi)
        self.bir.setGeometry(QtCore.QRect(50, 220, 41, 41))
        self.bir.setObjectName("bir")
        self.dort = QtWidgets.QPushButton(hesap_makinesi)
        self.dort.setGeometry(QtCore.QRect(50, 180, 41, 41))
        self.dort.setObjectName("dort")
        self.iki = QtWidgets.QPushButton(hesap_makinesi)
        self.iki.setGeometry(QtCore.QRect(100, 220, 41, 41))
        self.iki.setObjectName("iki")
        self.bes = QtWidgets.QPushButton(hesap_makinesi)
        self.bes.setGeometry(QtCore.QRect(100, 180, 41, 41))
        self.bes.setObjectName("bes")
        self.sekiz = QtWidgets.QPushButton(hesap_makinesi)
        self.sekiz.setGeometry(QtCore.QRect(100, 140, 41, 41))
        self.sekiz.setObjectName("sekiz")
        self.uc = QtWidgets.QPushButton(hesap_makinesi)
        self.uc.setGeometry(QtCore.QRect(150, 220, 41, 41))
        self.uc.setObjectName("uc")
        self.alti = QtWidgets.QPushButton(hesap_makinesi)
        self.alti.setGeometry(QtCore.QRect(150, 180, 41, 41))
        self.alti.setObjectName("alti")
        self.dokuz = QtWidgets.QPushButton(hesap_makinesi)
        self.dokuz.setGeometry(QtCore.QRect(150, 140, 41, 41))
        self.dokuz.setObjectName("dokuz")
        self.sifir = QtWidgets.QPushButton(hesap_makinesi)
        self.sifir.setGeometry(QtCore.QRect(50, 260, 91, 41))
        self.sifir.setObjectName("sifir")
        self.virgul = QtWidgets.QPushButton(hesap_makinesi)
        self.virgul.setGeometry(QtCore.QRect(150, 260, 41, 41))
        self.virgul.setObjectName("virgul")
        self.bire_gore_tersi = QtWidgets.QPushButton(hesap_makinesi)
        self.bire_gore_tersi.setGeometry(QtCore.QRect(150, 100, 41, 41))
        self.bire_gore_tersi.setObjectName("bire_gore_tersi")
        self.sifira_gore_tersi = QtWidgets.QPushButton(hesap_makinesi)
        self.sifira_gore_tersi.setGeometry(QtCore.QRect(100, 100, 41, 41))
        self.sifira_gore_tersi.setObjectName("sifira_gore_tersi")
        self.sifirla = QtWidgets.QPushButton(hesap_makinesi)
        self.sifirla.setGeometry(QtCore.QRect(50, 100, 41, 41))
        self.sifirla.setObjectName("sifirla")
        self.carpi = QtWidgets.QPushButton(hesap_makinesi)
        self.carpi.setGeometry(QtCore.QRect(200, 140, 41, 41))
        self.carpi.setObjectName("carpi")
        self.bolme = QtWidgets.QPushButton(hesap_makinesi)
        self.bolme.setGeometry(QtCore.QRect(200, 100, 41, 41))
        self.bolme.setObjectName("bolme")
        self.eksi = QtWidgets.QPushButton(hesap_makinesi)
        self.eksi.setGeometry(QtCore.QRect(200, 180, 41, 41))
        self.eksi.setObjectName("eksi")
        self.arti = QtWidgets.QPushButton(hesap_makinesi)
        self.arti.setGeometry(QtCore.QRect(200, 220, 41, 41))
        self.arti.setObjectName("arti")
        self.esittir = QtWidgets.QPushButton(hesap_makinesi)
        self.esittir.setGeometry(QtCore.QRect(200, 260, 41, 41))
        self.esittir.setObjectName("esittir")
        self.lcdNumber = QtWidgets.QLCDNumber(hesap_makinesi)
        self.lcdNumber.setGeometry(QtCore.QRect(50, 50, 191, 51))
        self.lcdNumber.setObjectName("lcdNumber")
        
        self.bir.clicked.connect(self.birclicked)
        self.iki.clicked.connect(self.ikiclicked)
        self.uc.clicked.connect(self.ucclicked)
        self.dort.clicked.connect(self.dortclicked)
        self.bes.clicked.connect(self.besclicked)
        self.alti.clicked.connect(self.alticlicked)
        self.yedi.clicked.connect(self.yediclicked)
        self.sekiz.clicked.connect(self.sekizclicked)
        self.dokuz.clicked.connect(self.dokuzclicked)
        self.sifir.clicked.connect(self.sifirclicked)
        self.sifirla.clicked.connect(self.cleanclicked)
        self.arti.clicked.connect(self.articlicked)
        self.eksi.clicked.connect(self.eksiclicked)
        self.bolme.clicked.connect(self.bolmeclicked)
        self.carpi.clicked.connect(self.carpiclicked)
        self.esittir.clicked.connect(self.esittirclicked)
        self.virgul.clicked.connect(self.virgulclicked)

        self.retranslateUi(hesap_makinesi)
        QtCore.QMetaObject.connectSlotsByName(hesap_makinesi)

    def retranslateUi(self, hesap_makinesi):
        _translate = QtCore.QCoreApplication.translate
        hesap_makinesi.setWindowTitle(_translate("hesap_makinesi", "Form"))
        hesap_makinesi.setWhatsThis(_translate("hesap_makinesi", "<html><head/><body><p><br/></p></body></html>"))
        self.yedi.setText(_translate("hesap_makinesi", "7"))
        self.bir.setText(_translate("hesap_makinesi", "1"))
        self.dort.setText(_translate("hesap_makinesi", "4"))
        self.iki.setText(_translate("hesap_makinesi", "2"))
        self.bes.setText(_translate("hesap_makinesi", "5"))
        self.sekiz.setText(_translate("hesap_makinesi", "8"))
        self.uc.setText(_translate("hesap_makinesi", "3"))
        self.alti.setText(_translate("hesap_makinesi", "6"))
        self.dokuz.setText(_translate("hesap_makinesi", "9"))
        self.sifir.setText(_translate("hesap_makinesi", "0"))
        self.virgul.setText(_translate("hesap_makinesi", ","))
        self.bire_gore_tersi.setText(_translate("hesap_makinesi", "%"))
        self.sifira_gore_tersi.setText(_translate("hesap_makinesi", "+/-"))
        self.sifirla.setText(_translate("hesap_makinesi", "AC"))
        self.carpi.setText(_translate("hesap_makinesi", "*"))
        self.bolme.setText(_translate("hesap_makinesi", "/"))
        self.eksi.setText(_translate("hesap_makinesi", "-"))
        self.arti.setText(_translate("hesap_makinesi", "+"))
        self.esittir.setText(_translate("hesap_makinesi", "="))
        
    def updatedisplay(self, value):
        current_value = self.lcdNumber.value()
        if current_value == 0.0:
            self.lcdNumber.display(int(value))
        else:
            self.lcdNumber.display(str(float(current_value)) + str(value))
                
    def virgulclicked (self):
        current_value = self.lcdNumber.value()
        self.lcdNumber.display(str(int(current_value)) + '.')
          
    def birclicked(self, value):
        current_value = self.lcdNumber.value()
        if current_value == 0.0:
            self.lcdNumber.display(1)
        else:
            self.lcdNumber.display(str(int(current_value)) + '1')
        
    def ikiclicked(self):
        current_value = self.lcdNumber.value()
        if current_value == 0.0:
            self.lcdNumber.display(2)
        else:
            self.lcdNumber.display(str(int(current_value)) + '2')
        
    def ucclicked(self):
        current_value = self.lcdNumber.value()
        if current_value == 0.0:
            self.lcdNumber.display(3)
        else:
            self.lcdNumber.display(str(int(current_value)) + '3')
        
    def dortclicked(self):
        current_value = self.lcdNumber.value()
        if current_value == 0.0:
            self.lcdNumber.display(4)
        else:
            self.lcdNumber.display(str(int(current_value)) + '4')
        
    def besclicked(self):
        current_value = self.lcdNumber.value()
        if current_value == 0.0:
            self.lcdNumber.display(5)
        else:
            self.lcdNumber.display(str(int(current_value)) + '5')
        
    def alticlicked(self):
        current_value = self.lcdNumber.value()
        if current_value == 0.0:
            self.lcdNumber.display(6)
        else:
            self.lcdNumber.display(str(int(current_value)) + '6')
        
    def yediclicked(self):
        current_value = self.lcdNumber.value()
        if current_value == 0.0:
            self.lcdNumber.display(7)
        else:
            self.lcdNumber.display(str(int(current_value)) + '7')
        
    def sekizclicked(self):
        current_value = self.lcdNumber.value()
        if current_value == 0.0:
            self.lcdNumber.display(8)
        else:
            self.lcdNumber.display(str(int(current_value)) + '8')
        
    def dokuzclicked(self):
        current_value = self.lcdNumber.value()
        if current_value == 0.0:
            self.lcdNumber.display(9)
        else:
            self.lcdNumber.display(str(int(current_value)) + '9')
        
    def sifirclicked(self):
        current_value = self.lcdNumber.value()
        if current_value == 0.0:
            self.lcdNumber.display(0)
        else:
            self.lcdNumber.display(str(int(current_value)) + '0')
        
    def cleanclicked(self):
        self.lcdNumber.display(0)
        
    def articlicked(self):
        self.current_operation = '+'
        self.result = self.lcdNumber.value()
        self.lcdNumber.display(0)
        
    def eksiclicked(self):
        self.current_operation = '-'
        self.result = self.lcdNumber.value()
        self.lcdNumber.display(0)
        
    def bolmeclicked(self):
        self.current_operation = '/'
        self.result = self.lcdNumber.value()
        self.lcdNumber.display(0)
        
    def carpiclicked(self):
        self.current_operation = '*'
        self.result = self.lcdNumber.value()
        self.lcdNumber.display(0)
    
    def esittirclicked(self):
        current_value = self.lcdNumber.value()
        
        if self.current_operation == '+':
            self.result += current_value
        elif self.current_operation == '-':
            self.result -= current_value
        elif self.current_operation == '/':
            self.result /= current_value
        elif self.current_operation == '*':
            self.result *= current_value
            
        self.lcdNumber.display(self.result)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hesap_makinesi = QtWidgets.QWidget()
    ui = Ui_hesap_makinesi()
    ui.setupUi(hesap_makinesi)
    hesap_makinesi.show()
    sys.exit(app.exec_())
