# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kelimebilgisi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_object(object):
    def setupUi(self, object):
        object.setObjectName("object")
        object.resize(600, 300)
        self.buyult = QtWidgets.QPushButton(object)
        self.buyult.setGeometry(QtCore.QRect(310, 150, 120, 30))
        self.buyult.setObjectName("buyult")
        self.karaktersayisi = QtWidgets.QPushButton(object)
        self.karaktersayisi.setGeometry(QtCore.QRect(190, 150, 120, 30))
        self.karaktersayisi.setObjectName("karaktersayisi")
        self.kelimegirisi = QtWidgets.QLineEdit(object)
        self.kelimegirisi.setGeometry(QtCore.QRect(250, 100, 113, 20))
        self.kelimegirisi.setObjectName("kelimegirisi")
        self.yazdir = QtWidgets.QLineEdit(object)
        self.yazdir.setGeometry(QtCore.QRect(250, 200, 113, 20))
        self.yazdir.setObjectName("yazdir")
        
        self.buyult.clicked.connect(self.buyult_clicked)
        self.karaktersayisi.clicked.connect(self.karaktersayisi_clicked)

        self.retranslateUi(object)
        QtCore.QMetaObject.connectSlotsByName(object)

    def retranslateUi(self, object):
        _translate = QtCore.QCoreApplication.translate
        object.setWindowTitle(_translate("object", "Dialog"))
        self.buyult.setText(_translate("object", "Buyult"))
        self.karaktersayisi.setText(_translate("object", "Karakter Say"))
        
    def buyult_clicked (self):
        mesaj = self.kelimegirisi.text()
        yeni_mesaj = mesaj.upper()
        self.yazdir.setText(yeni_mesaj)
        
    def karaktersayisi_clicked(self):
        mesaj = self.kelimegirisi.text()
        yeni_mesaj = str(len(mesaj))
        self.yazdir.setText(yeni_mesaj)
        
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    object = QtWidgets.QDialog()
    ui = Ui_object()
    ui.setupUi(object)
    object.show()
    sys.exit(app.exec_())
