# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_object(object):
    def setupUi(self, object):
        object.setObjectName("object")
        object.resize(400, 300)
        self.Yazdir = QtWidgets.QLineEdit(object)
        self.Yazdir.setGeometry(QtCore.QRect(50, 90, 113, 20))
        self.Yazdir.setObjectName("Yazdir")
        self.MerhabaYaz = QtWidgets.QPushButton(object)
        self.MerhabaYaz.setGeometry(QtCore.QRect(200, 85, 110, 30))
        self.MerhabaYaz.setObjectName("MerhabaYaz")

        self.MerhabaYaz.clicked.connect(self.MerhabaYazclicked)

        self.retranslateUi(object)
        QtCore.QMetaObject.connectSlotsByName(object)

    def retranslateUi(self, object):
        _translate = QtCore.QCoreApplication.translate
        object.setWindowTitle(_translate("object", "Merhaba"))
        self.MerhabaYaz.setText(_translate("object", "Merhaba Yaz"))
        
    def MerhabaYazclicked (self):
        self.Yazdir.setText("Merhaba QT ")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    object = QtWidgets.QDialog()
    ui = Ui_object()
    ui.setupUi(object)
    object.show()
    sys.exit(app.exec_())
